image:
  tag: "1.4.0-SNAPSHOT"

secrets:
  databaseSecret: neon-notification-db-secret-prod
  firebaseSecret: firebase-secret-prod

kafka:
  bootstrapServers: "kafka.kafka-prod.svc.cluster.local:9092"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 10

configServer:
  enabled: true

spring:
  profiles:
    active: prod

