image:
  repository: ghcr.io/systattic/traversium-notification-service
  tag: "1.3.0-SNAPSHOT"
  pullPolicy: Always

service:
  port: 8091
  type: ClusterIP

replicaCount: 1

secrets:
  imagePullSecret: ghcr-secret
  databaseSecret: neon-notification-db-secret
  firebaseSecret: firebase-secret

kafka:
  bootstrapServers: "kafka.kafka-test.svc.cluster.local:9092"
  notificationTopic: "notification-topic"
