apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traversium-ingress
spec:
  ingressClassName: ngnix
  rules:
    - http:
        paths:
      {{- range $key, $service := .Values.services }}
          - path: {{ $service.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $service.name }}
                port:
                  number: {{ $service.port }}
      {{- end }}