apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      {{ include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: notification-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{ include "common.firebaseVolumeMount" (dict "serviceName" "notification-service" "Values" .Values) | nindent 12 }}
          env:
            {{ include "common.standardEnv" (dict "contextPath" "/notifications" "Values" .Values) | nindent 12 }}
            - name: NOTIFICATION_BATCH_ENABLED
              value: "true"
            - name: NOTIFICATION_BATCH_WINDOW_MS
              value: "10000"
            - name: NOTIFICATION_BATCH_MIN_BATCH_THRESHOLD
              value: "3"
            - name: SPRING_KAFKA_NOTIFICATION_TOPIC
              value: "{{ .Values.kafka.notificationTopic }}"
          {{ include "common.probes" (dict "contextPath" "/notifications" "Values" .Values) | nindent 10 }}
      volumes:
        {{ include "common.firebaseVolume" . | nindent 8 }}
