config:
  inputs: |
    [INPUT]
        Name          tail
        Path          /var/log/containers/*.log
        Tag           kube.var.log.containers.*
        Mem_Buf_Limit 32MB


#  filters: |
#    [FILTER]
#        Name                kubernetes
#        Match               kube.var.log.containers.*
#        Kube_Tag_Prefix     kube.var.log.containers.
#        Kube_URL            https://kubernetes.default.svc:443
#        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
#        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
#        Merge_Log           On
#        Labels              On
#
#    [FILTER]
#        Name           nest
#        Match          kube.var.log.containers.*
#        Operation      lift
#        Nested_under   kubernetes
#        Add_prefix     k8s_
#
#    [FILTER]
#        Name   grep
#        Match  kube.var.log.containers.*
#        Regex  k8s_namespace_name ^default$

  outputs: |
    [OUTPUT]
        Name            es
        Match           *
        Host            elasticsearch-master
        Port            9200
        HTTP_User       elastic
        HTTP_Passwd     ${ELASTICSEARCH_PASSWORD}
        tls             On
        tls.verify      Off
        Logstash_Format On
        Suppress_Type_Name On
        Logstash_Prefix fluentbit

env:
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-master-credentials
        key: password
