apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: trip-service
  template:
    metadata:
      labels:
        app: trip-service
    spec:
      {{ include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: trip-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.service.grpcPort }}
          volumeMounts:
            {{ include "common.firebaseVolumeMount" (dict "serviceName" "trip-service" "Values" .Values) | nindent 12 }}
          env:
            {{ include "common.standardEnv" (dict "contextPath" "/trips" "Values" .Values) | nindent 12 }}
            - name: SPRING_KAFKA_AUDIT_TOPIC
              value: "{{ .Values.kafka.auditTopic }}"
            - name: SPRING_KAFKA_NOTIFICATION_TOPIC
              value: "{{ .Values.kafka.notificationTopic }}"
          {{ include "common.probes" (dict "contextPath" "/trips" "Values" .Values) | nindent 10 }}
      volumes:
        {{ include "common.firebaseVolume" . | nindent 8 }}
