apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        {{ include "common.prometheusAnnotations" (dict "contextPath" "/users" "Values" .Values) | nindent 8 }}
    spec:
      {{ include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: user-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{ include "common.firebaseVolumeMount" (dict "serviceName" "user-service" "Values" .Values) | nindent 12 }}
          env:
            {{ include "common.standardEnv" (dict "contextPath" "/users" "Values" .Values) | nindent 12 }}
            - name: SPRING_KAFKA_NOTIFICATION_TOPIC
              value: "{{ .Values.kafka.notificationTopic }}"
            - name: SPRING_KAFKA_AUDIT_TOPIC
              value: "{{ .Values.kafka.auditTopic }}"
            - name: GRPC_SERVER_HOST
              value: "{{ .Values.grpc.server.host }}"
            - name: GRPC_SERVER_PORT
              value: "{{ .Values.grpc.server.port }}"
          {{ include "common.probes" (dict "contextPath" "/users" "Values" .Values) | nindent 10 }}
      volumes:
        {{ include "common.firebaseVolume" . | nindent 8 }}