image:
  tag: "1.0.0-SNAPSHOT"
  pullPolicy: Always

secrets:
  databaseSecret: neon-report-db-secret-prod
  firebaseSecret: firebase-secret-prod

kafka:
  bootstrapServers: "kafka.kafka-prod.svc.cluster.local:9092"

configServer:
  enabled: true

spring:
  profiles:
    active: prod
