image:
  tag: "1.1.0-SNAPSHOT"

secrets:
  azureModerationSecret: azure-moderation-secret-prod

moderation:
  policy:
    blockSeverity: 2

security:
  oauth2:
    resourceserver:
      jwt:
        issuerUri: "http://keycloak-http.production.svc.cluster.local:8080/auth/realms/traversium"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 10

configServer:
  enabled: true
  

kafka:
    bootstrapServers: "kafka.kafka-prod.svc.cluster.local:9092"
