image:
  tag: "1.1.0-SNAPSHOT"

secrets:
  databaseSecret: neon-file-storage-db-secret-prod
  azureStorageSecret: azure-storage-secret-prod
  firebaseSecret: firebase-secret-prod

kafka:
  bootstrapServers: "kafka.kafka-prod.svc.cluster.local:9092"

azure:
  storage:
    containerName: "media-prod"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 10

configServer:
  enabled: true

spring:
  profiles:
    active: prod

