image:
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

secrets:
  azureStorageSecret: azure-storage-secret-dev
  firebaseSecret: firebase-secret-dev
  databaseSecret: neon-file-storage-db-secret-dev

azure:
  storage:
    containerName: "media-dev"

probes:
  startup:
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
  liveness:
    timeoutSeconds: 3
  readiness:
    periodSeconds: 5
    timeoutSeconds: 3

logging:
  level: DEBUG

spring:
  profiles:
    active: dev
