image:
  repository: ghcr.io/systattic/traversium-file-storage-service
  tag: "1.0.0-SNAPSHOT"
  pullPolicy: IfNotPresent

service:
  port: 8095
  type: ClusterIP

replicaCount: 1

secrets:
  imagePullSecret: ghcr-secret
  azureStorageSecret: azure-storage-secret
  firebaseSecret: firebase-secret

azure:
  storage:
    accountName: "traversium"
    containerName: "media"
    endpoint: "https://traversium.blob.core.windows.net/"

probes:
  startup:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 30  # 30 * 10 = 300 seconds max startup time
  liveness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
