image:
  tag: "latest"
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

secrets:
  databaseSecret: neon-social-db-secret-dev
  firebaseSecret: firebase-secret-dev
  keycloakSecret: keycloak-social-client-secret-dev

kafka:
  auditTopic: "audit-topic-dev"
  notificationTopic: "notification-topic-dev"

security:
  oauth2:
    client:
      tokenUri: "http://keycloak-http.dev.svc.cluster.local:8080/auth/realms/traversium/protocol/openid-connect/token"

probes:
  startup:
    initialDelaySeconds: 15
    periodSeconds: 5
    timeoutSeconds: 3
  liveness:
    timeoutSeconds: 3
  readiness:
    periodSeconds: 5
    timeoutSeconds: 3

logging:
  level: DEBUG
