image:
  tag: "1.2.0"

secrets:
  databaseSecret: neon-trip-db-secret-prod
  firebaseSecret: firebase-secret-prod

kafka:
  bootstrapServers: "kafka.kafka-prod.svc.cluster.local:9092"

probes:
  liveness:
    initialDelaySeconds: 10
    periodSeconds: 15
  readiness:
    initialDelaySeconds: 10
