apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      {{- include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{- include "common.firebaseVolumeMount" (dict "serviceName" "audit-service" "Values" .Values) | nindent 12 }}
          env:
            {{- include "common.standardEnv" (dict "contextPath" "/audit" "Values" .Values) | nindent 12 }}
            - name: SPRING_KAFKA_TOPIC
              value: "{{ .Values.kafka.auditTopic }}"
          {{- include "common.probes" (dict "contextPath" "/audit" "Values" .Values) | nindent 10 }}
      volumes:
        {{- include "common.firebaseVolume" . | nindent 8 }}
