apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
      name: http
    - port: {{ .Values.grpc.server.port }}
      targetPort: {{ .Values.grpc.server.port }}
      name: grpc
  selector:
    app: audit-service
