# Common/Default configuration

ingress:
  enabled: true
  className: "nginx"
  host: "api.traversium.com"
  tls:
    enabled: false
    secretName: ""
  annotations: {}

services:
  user:
    name: user-service
    path: /users
    port: 80
  notification:
    name: notification-service
    path: /notifications
    port: 80
  auditor:
    name: audit-service
    path: /audit
    port: 80
  trip:
    name: trip-service
    path: /trips
    port: 80
  social:
    name: social-service
    path: /social
    port: 80
  files:
    name: file-storage-service
    path: /files
    port: 80
  tenant:
    name: tenant-service
    path: /tenants
    port: 80
  report:
    name: reporting-service
    path: /reports
    port: 80
  keycloak:
    name: keycloak-http
    path: /auth
    port: 8080
  config:
    name: config-server
    path: /monitor
    port: 80