# Common/Default configuration

ingress:
  enabled: true
  className: "nginx"
  host: ""
  tls:
    enabled: false
    secretName: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

services:
  user:
    name: user-service
    path: /users
    port: 80
  notification:
    name: notification-service
    path: /notifications
    port: 80
  auditor:
    name: audit-service
    path: /audit
    port: 80
  trip:
    name: trip-service
    path: /trips
    port: 80
  social:
    name: social-service
    path: /social
    port: 80
  files:
    name: file-storage-service
    path: /files
    port: 80
  config:
    name: config-server
    path: /monitor
    port: 80