apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: file-storage-service
  template:
    metadata:
      labels:
        app: file-storage-service
      annotations:
        {{- include "common.prometheusAnnotations" (dict "contextPath" "/files" "Values" .Values) | nindent 8 }}
    spec:
      {{- include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: file-storage-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{ include "common.firebaseVolumeMount" (dict "serviceName" "filestorage-service" "Values" .Values) | nindent 12 }}
          env:
            {{ include "common.databaseEnv" . | nindent 12 }}
            {{ include "common.serverEnv" (dict "contextPath" "/files" "Values" .Values) | nindent 12 }}
            {{ include "common.flywayJpaEnv" . | nindent 12 }}
            {{ include "common.kafkaBootstrap" . | nindent 12 }}
            {{ include "common.managementEnv" . | nindent 12 }}
            {{ include "common.managementHealthWithDb" . | nindent 12 }}
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_NAME
              value: "{{ .Values.azure.storage.accountName }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_CONTAINER_NAME
              value: "{{ .Values.azure.storage.containerName }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT
              value: "{{ .Values.azure.storage.endpoint }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.azureStorageSecret }}
                  key: account-key

            - name: SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE
              value: "{{ .Values.spring.servlet.multipart.maxFileSize }}"
            - name: SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE
              value: "{{ .Values.spring.servlet.multipart.maxRequestSize }}"

            - name: TRIP_SERVICE_URL
              value: "{{ .Values.tripService.url }}"

            # Spring Cloud Config Server
            {{- if .Values.configServer }}
            {{- if .Values.configServer.enabled }}
            {{ include "common.configServerEnv" . | nindent 12 }}
            {{ include "common.configServerBusEnv" . | nindent 12 }}
            {{- end }}
            {{- end }}
          {{ include "common.probes" (dict "contextPath" "/files" "Values" .Values) | nindent 10 }}
      volumes:
        {{ include "common.firebaseVolume" . | nindent 8 }}
