apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-storage-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: file-storage-service
  template:
    metadata:
      labels:
        app: file-storage-service
    spec:
      {{- include "common.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: file-storage-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          volumeMounts:
            {{ include "common.firebaseVolumeMount" (dict "serviceName" "file-storage-service" "Values" .Values) | nindent 12 }}
          env:
            {{- include "common.serverEnv" (dict "contextPath" "/files" "Values" .Values) | nindent 12 }}
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_NAME
              value: "{{ .Values.azure.storage.accountName }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_CONTAINER_NAME
              value: "{{ .Values.azure.storage.containerName }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ENDPOINT
              value: "{{ .Values.azure.storage.endpoint }}"
            - name: SPRING_CLOUD_AZURE_STORAGE_BLOB_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.azureStorageSecret }}
                  key: account-key
          {{ include "common.probes" (dict "contextPath" "/files" "Values" .Values) | nindent 10 }}
      volumes:
        {{ include "common.firebaseVolume" . | nindent 8 }}
