apiVersion: v1
kind: Service
metadata:
  name: file-storage-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}
  selector:
    app: file-storage-service
